# Generated by Django 4.1.7 on 2023-02-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='events_subscribed', to='events.user'),
        ),
    ]
