# Generated by Django 4.1.7 on 2023-02-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
