# Generated by Django 4.1.7 on 2023-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='events_subscribed', to='events.user'),
        ),
    ]
